name: deploy-jupyter-book

on:
  push:
    branches:
      - main

env:
  python-version: 3.11.4

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Cache poetry
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build the book
        run: poetry run jupyter-book build ./docs

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
